In [1]:
import numpy as np 

taxi= np.genfromtxt("nyc_taxis.csv",delimiter = ",",skip_header=1) #delimiter should be specified 
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [2]:
bool_feb = taxi[:,1] == 2 #boolean array, checking for month of Feb
bool_feb.sum()

13333

In [3]:
taxi[bool_feb].shape[0] #total number of rides in February

13333

In [4]:
taxi[bool_feb,9:13]

array([[26.5 ,  1.3 ,  5.54,  0.  ],
       [11.5 ,  1.3 ,  0.  ,  2.  ],
       [30.5 ,  1.3 ,  0.  ,  6.35],
       ...,
       [52.  ,  0.8 ,  0.  ,  0.  ],
       [25.  ,  1.3 ,  5.54,  6.35],
       [22.  ,  1.3 ,  0.  ,  3.  ]])

In [5]:
tip_bool = taxi[:,12] > 5
taxi[tip_bool].shape[0]

50952

In [6]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a = np.arange(10) #making array in ascending order starting from 0
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
zero = np.zeros((taxi.shape[0],1)) #by default in place of 1 there is 0, which means this would be added as row but we want column
#zero = np.zeros((len(taxi).reshape(89560,1))
zero     

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [9]:
zero.ndim #tells dimension aka only rows here

2

In [10]:
zero.shape

(89560, 1)

In [11]:
taxi = np.concatenate([taxi,zero], axis = 1)
taxi[:,15]

array([0., 0., 0., ..., 0., 0., 0.])

In [12]:
ab = np.array([1,2,3,4,5])
ab

array([1, 2, 3, 4, 5])

In [13]:
ab[ab>3] = 10 #replacing with 10 where element greater than 3
ab

array([ 1,  2,  3, 10, 10])

In [16]:
#where pickup_location = 2,3,5 update 1 in 15th column(zero)
two = taxi[:,5] == 2
taxi[two,15] = 1
#taxi[two,15].shape
three = taxi[:,5] == 3
taxi[three,15] = 1
five = taxi[:,5] == 5
taxi[five,15] = 1
taxi[:,15]

array([1., 1., 1., ..., 1., 1., 1.])