In [1]:
import numpy as np 
from csv import reader

In [2]:
l = [1,2,3,4]
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [3]:
ar + 10

array([11, 12, 13, 14])

In [4]:
file = open("nyc_taxis.csv", encoding = "UTF-8")
read = reader(file)
taxi = list(read)
data = taxi[1:]
arr = np.array(data)
arr.astype("float64")
len(arr) #works on  array but preferable for list

89560

In [5]:
rc = arr.shape 
rc #numpy method which tells us rows and columns

(89560, 15)

In [6]:
arr.shape[0] #no. of rows

89560

In [7]:
arr[:,1] #on the left of comma; rows. right; columns. indexing/slicing can be done. this indicates all rows, but only first column

array(['1', '1', '1', ..., '6', '6', '6'], dtype='<U6')

In [8]:
# displaying 0-20 rows
arr[0:20]

array([['2016', '1', '1', '5', '0', '2', '4', '21.00', '2037', '52.00',
        '0.80', '5.54', '11.65', '69.99', '1'],
       ['2016', '1', '1', '5', '0', '2', '1', '16.29', '1520', '45.00',
        '1.30', '0.00', '8.00', '54.30', '1'],
       ['2016', '1', '1', '5', '0', '2', '6', '12.70', '1462', '36.50',
        '1.30', '0.00', '0.00', '37.80', '2'],
       ['2016', '1', '1', '5', '0', '2', '6', '8.70', '1210', '26.00',
        '1.30', '0.00', '5.46', '32.76', '1'],
       ['2016', '1', '1', '5', '0', '2', '6', '5.56', '759', '17.50',
        '1.30', '0.00', '0.00', '18.80', '2'],
       ['2016', '1', '1', '5', '0', '4', '2', '21.45', '2004', '52.00',
        '0.80', '0.00', '52.80', '105.60', '1'],
       ['2016', '1', '1', '5', '0', '2', '6', '8.45', '927', '24.50',
        '1.30', '0.00', '6.45', '32.25', '1'],
       ['2016', '1', '1', '5', '0', '2', '6', '7.30', '731', '21.50',
        '1.30', '0.00', '0.00', '22.80', '2'],
       ['2016', '1', '1', '5', '0', '2', '5', '36.30

In [9]:
# displaying first three columns of 0-20 rows
len(arr[0:20,0:3])

20

In [10]:
# displaying first 5 columns
arr[:,0:5]

array([['2016', '1', '1', '5', '0'],
       ['2016', '1', '1', '5', '0'],
       ['2016', '1', '1', '5', '0'],
       ...,
       ['2016', '6', '30', '4', '5'],
       ['2016', '6', '30', '4', '5'],
       ['2016', '6', '30', '4', '5']], dtype='<U6')

In [11]:
length = arr[:,8] #retrieves all rows of particular column; trip length

In [12]:
#converting seconds into hour
lengthf = length.astype("float64")
length_hr = lengthf/3600
length_hr

array([0.56583333, 0.42222222, 0.40611111, ..., 0.78388889, 0.30083333,
       0.47527778])

In [13]:
#calculating speed in miles per hour
miles = arr[:,7]
milesf = miles.astype("float64")
miles_per_hour = milesf/length_hr
miles_per_hour

array([37.11340206, 38.58157895, 31.27222982, ..., 22.29907867,
       42.41551247, 36.90473407])

In [14]:
mean_miles = sum(miles_per_hour)/len(miles_per_hour)
mean_miles

32.24258580925637

In [15]:
meanmph = miles_per_hour.mean() #numpy has mean function which saves from summing and division
meanmph

32.24258580925573

In [17]:
miles_per_hour.max()
miles_per_hour.min()

0.0

In [18]:
#summing columns 9-12 to give result equal to column 13
a = arr[:,9]
b = arr[:,10]
c = arr[:,11]
d = arr[:,12]
af = a.astype("float64")
bf = b.astype("float64")
cf = c.astype("float64")
df = d.astype("float64")
total = af + bf + cf + df
totalsum = total.sum()
totalsum


4385436.08

In [49]:
totalamount = arr[:,13]
totalamount = totalamount.astype("float64")
totalamount.sum()

4385454.29